#! /bin/bash

obmenu-generator -u -p -c -i
nitrogen --restore
pulseaudio --start

pgrep picom || picom &
pgrep dunst || dunst &
pgrep tint2 || tint2 &
pgrep conky || conky &
pgrep nm-applet || nm-applet &
pgrep pa-applet || pa-applet &
pgrep pc-web-dash || pc-web-dash &